### ISSUE TITLE
How can I get the password of data.zip of IEMOCAP ?

### ISSUE THREAD

**Issue by Aria-K-Alethia** [wenliangdai/Modality-Transferable-MER#2]
Thank you for sharing your code !
I downloaded the iemocap data from the given link.
But `data.zip` needs password to uncompress, how can I get it ?

**Comment by wenliangdai** [comment]
Hi, that data.zip is provided by this project https://github.com/A2Zadeh/CMU-MultimodalSDK

From my previous experience, you need to send a request to the original IEMOCAP author (check it here https://sail.usc.edu/iemocap/iemocap_release.htm), after you get it, you can send an email to the author of https://github.com/A2Zadeh/CMU-MultimodalSDK to get the password.

**Comment by Aria-K-Alethia** [comment]
> Hi, that data.zip is provided by this project https://github.com/A2Zadeh/CMU-MultimodalSDK
> 
> From my previous experience, you need to send a request to the original IEMOCAP author (check it here https://sail.usc.edu/iemocap/iemocap_release.htm), after you get it, you can send an email to the author of https://github.com/A2Zadeh/CMU-MultimodalSDK to get the password.

OK, thank you for your help !
