### ISSUE TITLE
RuntimeError: multi-target not supported for CrossEntropyLoss

### ISSUE THREAD

**Issue by Aria-K-Alethia** [wenliangdai/Modality-Transferable-MER#3]
After I checked your code, I think this error may because your command written in README is wrong.
Since CMU-MOSEI is a multi-label classification task, we need to use binary cross entropy loss, so the command for CMU-MOSEI should use bce loss instead of ce. And the command for IEMOCAP also has this problem.

BTW, why you also use binary cross entropy for IEMOCAP instead of normal cross entropy ?
=====Below is old message=====
Hello, 
I'm trying to run your model on the CMU-MOSEI dataset. And I got the multi-target error.
It seems the emotion label of processed dataset is not one-hot but multi-target.
Do you have any idea to fix this problem ?

**Comment by wenliangdai** [comment]
@Aria-K-Alethia 
Hi, yes you are right. I'll update the README soon.

The reason I use BCE for IEMOCAP is to compare with previous papers, they report binary performance and some papers state explicitly that they treat IEMOCAP as a multi-label dataset.

**Comment by Aria-K-Alethia** [comment]
> @Aria-K-Alethia
> Hi, yes you are right. I'll update the README soon.
> 
> The reason I use BCE for IEMOCAP is to compare with previous papers, they report binary performance and some papers state explicitly that they treat IEMOCAP as a multi-label dataset.

I see. Thank you for your help !
